## 7.1 任务的取消
如果外部代码可以将某个活动在其正常完成状态前移到完成状态，那么该活动是可以取消的。有许多原因使得你可能想取消一个活动：  
- **用户请求取消**。如在使用图形用户界面应用时，用户通过点击取消按钮或者通过一个类似于jmx的管理接口请求取消； 
- **限制时间的活动**。一个应用程序在给定的有限时间内寻找问题解空间，然后选择在这段时间内所找到的最好的解决方案。当定时器设定的时间消逝，任何仍在搜索解决方案的任务将取消；
- **应用事件**。一个应用通过将拆分问题为一系列不同的子任务来寻找问题空间的不同区域。当一个子任务寻找到解决方案，所有其它仍然在寻找方案的任务将被取消；
- **错误**。一个web爬虫寻找相关的网页，将网页或概要数据保存到硬盘上。当一个爬虫任务遇到一个错误（例如，磁盘已满），其它的正在爬数据的任务将被取消，可能会记录它们当前的状态以便稍后重新开始；  
- **关闭**。当一个应用或者服务被关闭，对于那些正在被处理的工作及那些等待处理的工作，应当做些什么。优雅的关闭时，那些当前正在执行的任务应该允许他们完成；立即关闭的情况，当前正在执行的任务可能被取消。
	
在java中，没有安全的办法来抢占式地停止一个线程，因此也没有安全的办法来抢占式地停止一个任务。在java中，只有协作机制，通过这种方式，任务和请求任务取消的代码遵循一个一致的协议。
	
这种协作机制的一种方式是设置一个任务取消被请求的标志，任务周期性地检查该标志；如果任务发现该标志设置了，该任务便提前终结。[Listing7.1]()中的PrimeGenerator,它在被取消前一直列举质数，说明了这一技巧。`cancel`方法设置`cancelled`标志，主循环在搜索下一个质数前检查这一标志。（为了这一技术能够可靠的工作，`cancelled`必须设置为`volatile`修饰的字段，保证对该标志位修改能够被其它线程看到）

[Listing7.2]()展示了该类的一个示例用法，让质数生成器PrimeGenerator运行一秒后取消它。该生成器未必在确切的一秒钟后停止，由于在任务被请求取消与主循环检查该任务是否被取消之间可能有一些延迟。`cancel`方法在一个finally语句块中被调用，从而确保即使对`sleep`方法的调用被中断了，质数生成器仍然会被取消。如果`cancel`方法不被调用，该寻找质数的线程将一直运行下去，消耗cpu时间片，阻止java虚拟机进程的退出。

一个想要能够被取消的任务必须有一个取消政策，该政策指明了怎样取消，何时取消，取消时做些什么——其它代码可以怎样请求取消该任务，该任务什么时候检查取消被请求了，该任务该做些什么来响应一个取消请求。

考虑一个停止支付现金的真实例子。银行有关于如何提交一个停止支付请求，在处理这种请求时需要保证的怎样的响应性，当一次支付被真正取消时该遵循怎样的步骤（诸如通知其它涉及到这次交易的银行以及根据支付者的账户评估一个费用），这些步骤及保证组成了支付的取消原则。
	
#### Listting7.1 使用一个volatile字段来持有取消状态
```
	@ThreadSafe
	public class PrimeGenerator implements Runnable{
		@GuardedBy(“this”) 
		private final List<BigInteger> primes=new ArrayList<BigInteger>();
		private volatile cancelled;
		public void run(){
			BigInteger p=BigInteger.ONE;
			while(!cancelled){
				p=p.nextProbablePrime();
				synchronized(this){
					primes.add(p);
				}
			}
		}
		public void cancel(){
			cancelled=true;
		}
		public synchronized List<BigInteger> get(){
			return new ArrayList<BigInteger>(primes);
		}
	}
```
#### Listing7.2 一秒钟内生成的质数
```
	List<BigInteger> aSecondOfPrimes() throws InterruptedException{
		PrimeGenerator generator=new PrimeGenerator();
		new Tnread(generator).start();
		try{
			SECONDS.sleep(1);
		}finally{
			generator.cancel();
		}
		return generator.get();
	}
```
PrimeGenerator使用一个简单的取消政策：客户端代码通过调`cancel`方法来请求取消，PrimeGenerator每当一个质数找到就检测是否取消，当它检测到取消请求时就退出。

### 7.1.1 中断
质数生成器中的取消机制最终将导致寻找质数的任务退出，虽然这可能会要一小会时间。然而，如果一个使用这种方式的任务调用了一个像BlockingQueue的`put`方法这样的阻塞方法，我们可能有一个更严重的问题——任务可能永远不会检查取消标志，因此可能永远不会终止。

[Listing1.3]()中的BrokenPrimeProducer说明了这个问题。生产者线程产生质数并将它们存放在一个阻塞队列中。如果该生产者产生质数的速度大于消费者从队列中取出质数的速度，该队列最终会填满，`put`方法将被阻塞住。如果消费者试图取消生产者任务而此时生产者正阻塞在`put`方法时，会发生什么？它可以调用`cancel`方法来将`cancelled`标志设置为`true`——但是生产者将永远不会检查这一标志，因为它将永远不会从被阻塞的`put`方法中解脱出来（因为消费者已经停止从队列中取出质数）。

我们在第五章曾指出，某些阻塞的库方法支持中断。线程中断是一种协作机制，一个线程用线程中断来向另一个线程发出信号，告知该线程它应该在它方便时，或者如果它愿意的话，停止它现在手头正在做的，做些其它别的事。
```
虽然java API和java语言规范中没有将中断与任何具体的取消绑在一起，然而，实际上，使用中断来做取消之外的任何事都是脆弱的，并且在大的应用中很难维持。
```

每个线程都有一个`boolean`类型的`interrupted`状态字段；中断一个线程会把该字段设置为`true`.正如[Listing7.4]()所示,线程类包含有中断线程和查询线程中断状态的方法。`interrupt`方法中断目标线程的状态，`isInterrupted`方法返回目标字段的中断状态。拙劣的命名为`interrupted`的静态方法清空当前线程的中断状态，返回它前一次的值，该方法是清空中断状态的唯一方式。

像`Thread.sleep`和`Object.wait`这样的阻塞式库方法试图去检测一个线程什么时候被请求中断，然后早早地返回。它们通过清除中断状态字段值，抛出一个被中断异常这种方式来响应中断，表明阻塞式的操作由于中断而提前完成。Java虚拟机没有对一个阻塞式方法多快检测中断作出保证，但实际上，对中断的检测通常相当快。

#### Listing7.3 不可靠的取消，导致Producers卡在了阻塞式操作中。不要这么做。
```
	class BrokenPrimeProducer extends Thread{
		private final BlockingQueue<BigInteger> queue;
		private volatile Boolean cancelled=false;
		BrokenPrimeProducer(BlockingQueue<BigInteger> queue){
			this.queue=queue;
		}
		public void run(){
			try{
				BigInteger p=BigInteger.ONE;
				while(!cancelled){
					queue.put(p=p.nextProbablePrime());
				}
			}catch(InterruptedException cousumed){
			}		
		}
		public void cancel(){
			cancelled=true;
		}
	}

	void consumePrimes() throws InterruptedException{
		BlockingQueue<BigInteger> primes=…;
		BrokenPrimeProducer producer=new BrokenPrimeProducer(primes);
		producer.start();
		try{
			while(needMorePrimes()){
				consume(primes.take());
			}
		}finally{
			producer.cancel();
		}
	}
```
#### Listing 7.4. Thread类中中断相关的方法
```
	public class Thread{
	public void interrupt(){…}
	public boolean isInterrupted(){…}
	public static Boolean interrupted(){…}
	}
```
如果一个线程在未阻塞时被中断，它的`interrupted`状态字段会被设置，由正在被取消的活动来检查`interrupted`字段发现中断。采用这种方式，中断是粘性的——如果它没有触发一个`InterruptedException`，中断的证据将一直保留直到某人谨慎地清除掉被中断状态。
```	
调用`interrupt`方法未必让目标线程停止正在做的事情；它仅仅是传递一个信息：中断被请求了。
```	
关于中断的一个更好的看法是它不是真正地中断一个正在运行的线程，它只是请求线程在下一个合适的时机中断自身（这些时机叫做取消点）。一些方法，诸如`wait,sleep,join`，认真对待该请求，当它们接收到一个中断请求或在方法入口遇到一个已经设置的`interrrupted`状态字段时抛出一个异常。表现好的方法可能完全忽略中断请求只要他们将中断请求保留以便调用代码能够对该中断请求做些什么。槽糕的方法吞下中断请求，因此使得调用栈更高层的代码没有机会对该中断请求做些什么。
	
静态的`interrupted`方法需要谨慎使用，因为它清空了当前线程的中断状态字段的值。如果你调用`interrupted`方法，并返回`true`,除非你打算吞下该中断请求，否则你应该对此做些什么——或者抛出被中断异常，或者像94页[Listing5.10]()那样，再次调用`interrupt`方法来恢复`interrupted`状态字段的值。
	
BrokenPrimeProducer展示了定制的取消机制是如何并不总能够与阻塞式的库方法很好地协作。如果你编码你的任务来对中断请求作出响应，你可以利用众多的库方法提供的中断支持。
```	
中断通常是实现取消的最合理的方式。
```
BrokenPrimeProducer可以很容易修复，通过使用中断取代那种用一个`boolean`类型的标志字段来请求取消的方式，同时也简化了代码，如下[Listing7.5]()所示。
#### Listing7.5 使用中断来取消
```
	class PrimeProducer extends Thread{
		private final BlockingQueue<BigInteger> queue;
		PrimeProducer(BlockingQueue<BigInteger> queue){
			this.queue=queue;
		}
		public void run(){
			try{
				BigInteger p=BigInteger.ONE;
				while(!Thread.currentThread().isInterrupted()){
					queue.put(p=p.nextProbablePrime());
				}
			}catch(InterruptedException consumed)[
				/*Allow thread to exit*/
			}
		}
		public void cancel(){
			interrupt();
		}
	}
```
### 7.1.2 线程中断政策

线程应该有一个中断执行的政策，如同任务应该有一个取消政策一样。一个中断政策决定了一个线程如何解释（看待）一个中断请求——当检测到一个中断请求时，它做些什么（如果需要的话），相对于一次中断，它的哪些工作应该看作是原子的（或者说，它的哪些工作是不可以被中断的，需要被当做一个整体），它对中断的响应速度如何。
	
最合理的中断政策是某种形式上的线程级别或者服务级别的取消：尽可能快地退出（满足实际的实践需求），做一些必要的清理，可能会通知一些拥有该线程的实体该线程正在退出。虽然可以建立一些别的中断政策，诸如暂停或继续一个服务，但是使用非标准的中断政策的线程或线程池可能局限于只能传递那些清楚这些线程或线程池所使用的中断政策而编写的任务以供执行。	
	
区分任务和线程各自应该如何对中断做出反应是非常重要的。一个中断请求可能有不止一个的期望接受者——中断一个线程池中的工作线程可能意味着既要取消该工作线程当前正在执行的任务，同时还要关闭改工作线程。
	
任务不是在他们自身拥有的线程中执行，它们向一个诸如线程池这样的服务租借线程来执行任务。不拥有该线程的代码（例如，就线程池而言，任何线程池实现之外的代码）要注意保留线程的中断状态，这样拥有该线程的代码最终能够对此作出响应，即使客户代码也对此中断作出了一些响应动作。（如果你为某人照看房子，你不能将在他们离开后收到的邮件扔掉——你将它们保管好，让他们回来后处理这些邮件，即使你确实看了他们的杂志。）
	
这也解释了为什么大多数类库阻塞方法仅仅简单地抛出`InterruptedException`作为对中断的响应。因为它们将不会执行在一个它们自身拥有的线程中，所以它们实现了对于任务或类库代码来说最合理的取消政策：尽快退出，将中断消息传递给调用者以便调用栈更高层的代码能够采取进一步的动作。
	
当任务觉察到一个中断请求时，它不必立即放弃一切——它可以选择记住它被中断了，推迟到一个更适宜的时机结束它正在执行的任务，然后抛出一个`InterruptedException`或者其他的指示中断的方式。这一技巧可以避免当一个正在更新中的活动被中断时，数据结构被损坏。
	
任务不应假设它的执行线程的中断政策，除非它被显式的设计运行在一个拥有特定的中断政策的服务中。不管任务将中断视为取消还是采取一些其他的行动，它都应该注意将正在执行的线程的中断状态保留。如果它不是简单地将`InterrruptedException`传播给它的调用者，他应该在捕获`InterruptedException`后恢复中断状态：
```
	    Thread.currentThread.interrupt();
```
正如任务代码不应假设中断对于执行该任务的线程意味着什么，和取消相关的代码不应该对任意线程的中断政策作出假设。只有线程的所有者能够中断线程；线程的所有者可以以一种恰当的取消机制来封装线程的中断原则方面的内容，例如提供一个`shutdown`方法。
```	
因为每个线程有各自的中断政策，你不应该中断一个线程除非你知道中断对于那个线程意味着什么。
```	
批判家们嘲笑java的中断机制，因为它不能提供一个抢占式的中断能力，而是强迫开发者来处理`InterruptedException`。然而，推迟中断请求的能力使得开发者们能够设计灵活的，对于应用来说在响应和健壮性方面适宜的中断原则。
	
### 7.1.3 对中断的响应

在[5.4部分]()提到，当你调用一个诸如`Thread.sleep`或`BlockingQueue.put`方法这样可以被中断的阻塞式方法时，有两种可行的处理被中断异常的策略：
	
	

- 传播该异常（可能在完成特定于该任务的相关清理工作之后），使你的方法也成为一个可被中断的阻塞式方法；
	
	

- 恢复中断字段的状态以便调用栈更高层的代码能够处理该中断请求;
	
传播被中断异常可以简单地添加被中断异常到throws子句。像下面的[Listing7.6]()的getNextTask方法显示的那样：
####Listing 7.6 传播被中断异常给调用者
```
BlockingQueue<Task> queue;
	…
	public Task getNextTask() throws InterruptedException{
		return queue.take();
	}
```	
如果你不想或者不能传播被中断异常（也许是由于你的任务通过Runnable接口来定义的），你需要找到另一种方法来保存该中断请求。标准的做法是通过再次调用`interrupt`来恢复该中断状态。你不应该捕获InterrruptedException，然后在捕获块（catch）中什么也不做，咽下该InterruptedException，除非你的代码确实是在实现一个线程的中断政策。PrimeProducer吞下了该中断，但是这样做是因为知道线程将要终结，因此调用栈上没有更高层代码需要知道该中断了。大多数代码不知道它将运行于那个线程，因此应该保存该中断状态。
```
只有实现线程的中断原则的代码可以吞下一个中断请求。通用的任务或者库代码绝不能吞下中断请求。
```
不支持取消但仍然调用可以被中断的阻塞方法的那些活动将不得不在一个循环中调用这些可以被中断的阻塞方法，当中断被检测到时，重新执行循环体中的代码。在这种情况下，它们应该通过局部变量保存中断状态，然后在方法返回之前恢复该中断状态，像[Listing7.7]()所展示的那样，而不是一捕获`InterruptedException`就调用`interrupt`方法来恢复中断状态。过早地设置被中断状态可能导致一个无限死循环，因为大多数可以被中断的阻塞方法在进入该方法时检查被中断状态，如果该字段被设置为true的话立即抛出线程被中断异常InterruptedException.(可被中断的方法通常为了尽可能快地对中断作出响应，在阻塞或者做任何重要的工作前审查中断状态)

如果你的代码不能调用可被中断的阻塞方法，它仍然可以通过在任务代码中审查当前线程的被中断状态来对中断作出响应。需要在效率和响应性之间做取舍来设置审查频率。如果你有高响应性方面的要求，你不能调用那些潜在的可能需要运行很长时间而它们自身不能对中断作出响应的方法，潜在地限制了你对一些库方法的调用。
	
取消可能牵涉到除了中断状态之外的情形；中断可以用来获得被中断线程的注意，那些被正在调用中断方法的线程保存在其他地方的信息可以用来为被中断的线程提供更进一步的指示。（访问这些信息时，请确保使用了同步机制synchronization）。
#### Listing7.7 在退出之前恢复中断的不可取消的任务
```	
public Task getNextTask(BlockingQueue<Task> queue){
		boolean interrupted=false;
		try{
			while(true){
				try{
					return queue.take();
				}catch(InterruptedException e){
					interrupted=true;
					//失败并重新尝试
				}
			}
		}finally{
			if(interrupted){
				Thread.currentThread().interrupt();
			}
		}
	}
```
例如，当一个ThreadPoolExecutor拥有的工作线程检测到中断请求，它会查看线程池是否正在被关闭。如果是的话，它会在结束前执行一些线程池的清理工作；否则它会创建一个新的线程来维持线程池的期望大小。
### 7.1.4例子：TimedRun
很多问题的解决可能需要花费无限长的时间（例如：枚举所有的质数）；对于其他的问题，答案可能很快被找到也可能耗费很久。在这些场景中，能够说“花费至多十分钟来寻找答案”或“在十分钟内列举出你知道的所有答案”可能很有用。

[Listing7.2]()中的aSecondOfPrimes方法开启了一个PrimeGenerator(质数生成器)线程，然后在一秒钟之后中断了它。尽管该PrimeGenerator可能会花费不止一秒钟来停止，它最终会察觉该中断请求并停止，以允许线程终结。但是执行一项任务的另一方面是你想要查明该任务是否会抛出一个异常。如果PrimeGenerator在设置的超时时间消逝前抛出一个未受检的异常，它可能不被察觉，因为该质数生成器在一个分开的未显示地处理异常的线程中执行。
	
[Listing7.8]()展示了在给定的时间内运行一个任意的Runnable的一个尝试。它在调用线程中运行任务，然后安排一个取消任务来在指定的时间间隔后中断它。这解决了任务中抛出非受检异常的问题，因为它们可以被方法timedRun的调用者捕获。

这是一种即吸引人又简单的方式，但是它违背了规则：你应该在中断一个线程之前清楚该线程的中断原则。既然timedRun可能被任意一个线程调用，它不可能清楚调用它的线程的中断原则。如果任务在设定的超时时间前完成，在timedRun已经返回到它的调用者后，那个用来中断timedRun被调用的线程的取消任务就会跑偏。我们不知道当那种情况发生时会执行什么代码，但是结果不可能会是好的。（）
#### Listing 7.8 在一个借来的线程上安排一个中断。不要这么做。
```
private static final ScheduledExecutorService cancelExec=...;
public static void timedRun(Runnable r,long timeout,TimeUnit unit){
	final Thread taskThread=Thread.currentThread();
	cancelExec.schedule(new Runnable(){
				public void run(){
					taskThread.interrupt();	
				}
			    },timeout,unit);
	r.run();
}
```
此外，如果任务不响应中断的话，timedRun方法将直到任务结束才返回，这可能在期望的时间过去之后很久（甚至可能不会返回）。一个timed run服务在指定的时间过去之后不能返回很可能惹恼它的调用者。

[Listing 7.9]()解决了aSecondOfPrimes的异常处理问题和之前的尝试带来的问题。为了运行该任务而被创建的线程可以有它自己的执行原则，即使该任务不能对中断作出响应，timed run方法仍然可以返回到它的调用者。在启动该任务线程后，timedRun方法调用新创建的线程的timed join方法。当join方法返回后，它会检查异常是否是从任务代码中抛出来的，如果是的话，在调用timedRun方法的线程中重新抛出该异常。保存的Throwable在这两个线程中共享，因此它被声明为volatile字段，从而能够安全地从任务线程发布到timedRun线程。

该版本解决了之前的例子中的问题，但是因为它的实现依赖一个timed join方法，它便有join方法带来的不足：我们不知道控制权返回调用线程是因为被调用join方法的线程的正常退出还是因为join方法超时。
#### Listing7.9. 中断在一个专门执行该任务的线程中的任务
```
public static void timedRun(final Runnable r,long timeout,TimeUnit unit) throws InterrputedException{
	class RethrowableTask implements Runnable{
		private volatile Throwable t;
		public void run(){
			try{
				r.run()
			}catch(Throwable t){
				this.t=t;
			}
		}
		void rethrow(){
			if(t!=null){
				throw launderThrowable(t);
			}
		}
	}
		
	RethrowableTask task=new RethrowableTask();
	final Thread taskThread=new Thread(task);
	taskThread.start();
	cancelExec.schedule(new Runnable(){
		taskThread.interrupt();
	},timeout,unit);
	taskThread.join(unit.toMillis(timeout));
	task.rethrow();
}
```
### 7.1.5 通过Future来取消任务
我们已经使用过一种用来管理任务的生命周期，处理异常，和取消任务的抽象——Future.遵循通用的原则：不要重复造轮子，相比于自己创造一个，使用类库中已经存在的类更好。让我们使用Future和任务执行框架来构建timeRun方法.

ExecutorService接口的submit方法会返回一个Future实例来描述任务。Future接口有一个cancel方法，该方法接受一个boolean类型的参数，mayInterruptIfRunning,返回一个值表明关于取消的尝试是否成功（这仅是告诉你它是否能发送中断请求，而不是任务是否检测到该中断请求并对该中断请求做些什么）。当mayInterruptIfRunning为true并且任务当前正在某个线程中运行时，那么那个线程将被中断。将该参数设置为false意味着“如果该任务还未开始，不要运行该任务”，因此应该被用于那些未设计处理中断的任务。

既然除非你知道线程的中断原则，否则不要中断它。那么什么时候可以使用参数true来调用cancel方法？标准的Executor实现创建的任务执行线程实现了一个中断原则，该中断原则允许任务使用中断来取消，所以当它们运行在标准Executor中时，通过设置mayInterruptIfRunning，用它们的Futures来取消任务是安全的。你不应该在试图取消一个任务时，采取直接中断一个线程池中的线程的方式，因为你不知道当中断请求发出时，什么任务正在运行中——只能通过Future的cancel方法来做这。这也是编程任务将中断视作一个取消任务的请求的另一原因：这样他们可以通过它们的Futures来取消。
[Listing 7.10]()展示了timedRun方法的另一个版本，该版本将任务提交给ExecutorService，通过Future的设定超时的get方法获取结果。如果get方法伴随着TimeOutException而终止，该任务通过它的Future来取消。（为了简化编码，这个版本在一个finally块中无条件的调用Future的cancel方法，利用了一个事实：无法取消一个已经完成的任务）如果潜在的计算在取消任务之前抛出一个异常，它将从timedRun方法中重新抛出，这是让调用者处理异常的最方便的方法。[Listing 7.10]()也展示了另一个好的实践：取消那些结果不再需要的任务。（128页的[Listing 6.13]()和132页的[Listing 6.16]()也使用到这一技术）
#### Listing7.10. 使用Future取消任务
```
public static void timedRun(Runnable r,long timeout,TimeUnit unit) throws InterruptedException{
	Future<?> task=taskExec.submit(r);
	try{
		task.get(timeout,unit);
	}catch(TimeoutException e){
		//task will be cancelled below
	}catch(ExecutionException e){
		//任务中抛出的异常，重新抛出
		throw launderThrowable(e.getCause());
	}finally{
		//Harmless if task already completed
		task.cancel(true);//interrupt if running
	}
}
```
```
当Future的get方法抛出InterruptedException或者TimeoutException，并且你知道程序不再需要改任务的结果时，调用Future.cancel方法来取消任务。
```

### 7.1.6. 处理不能被中断的阻塞
大多数阻塞的类库方法会通过及早地返回并抛出一个InterruptedException来响应中断，这使得构造响应取消的任务变得简单多了。然而，不是所有的阻塞方法或者阻塞机制都能响应中断；如果一个线程阻塞来执行同步的套接字I/O或者等待获取一个内在锁，中断除了设置线程的中断状态外，没有其它作用。有时候我们可以让阻塞在不可中断的活动中的线程停止通过类似于中断的方式，但是这要求对该线程为什么阻塞有更好的认识。


- **java.io中的同步的socket I/O**在服务端应用中阻塞性I/O的常见形式是向一个套接字Socket中读或者写。不幸的是，InputStream和OutputStream中的read和write方法无法响应中断，但是关闭潜在的socket能够使任何阻塞在read或者write方法中的线程抛出一个SocketException.


- **java.nio中的同步I/O**中断一个正在等待一个可被中断的通道的线程将导致该线程抛出一个ClosedByInterruptException并关闭该通道（同时也将会导致别的阻塞在该通道的线程抛出ClosedByInterruptException）.关闭一个InterruptibleChannel导致阻塞在该通道操作的线程抛出AsynchronousCloseException。大多数标准的Channels实现了InterruptibleChannel接口。


- **异步的I/Owith Selector**如果一个线程阻塞在Selector.select(in java.nio.channels),调用close或者wakeup方法将导致它提前返回。


- **Lock acquisition**.如果一个线程因为等待获取一个内在锁而阻塞的话，没有任何方法可以让它停止，除了确保它最终会获得那个锁，执行到你用其他方式获得该线程的注意的代码处。然而，显式的锁类提供了lockInterruptibly方法，该方法允许你等待获取一个锁的同时，仍然能够响应中断。——见[13章]()

[Listing 7.11]()中的ReaderThread展示了一种封装非标准取消的技术。
#### Listing 7.11. 通过覆写interrupt方法将非标准取消方式封装到线程中
```
public class ReaderThread extends Thread{
	private final Socket socket;
	private final InputStream in;
	public ReaderThread(Socket socket) throws IOException{
		this.socket=socket;
		this.in=socket.getInputStream();
	}
	public void interrupt(){
		try{
			socket.close();	
		}catch(IOException ignored){
		}finally{
			super.interrupt();
		}
	}
	public void run(){
		try{
			byte[] buf=new byte[BUFSZ];
			while(true){
				int count=in.read(buf);
				if(count<0){
					break;
				}else if(count>0){
					processBuffer(buf,count);
				}
			}
			
		}catch(IOException e){
			/*Allow thread to exit */
		}
	}
}
```
ReaderThread管理一个单个的socket连接，从该socket中同步读取，将接受到的数据传递给processBuffer方法。为了实现终止用户连接或关闭服务器，ReaderThread覆写了interrupt方法来发送一个标准的中断请求同时关闭潜在的socket;因此中断ReaderThread将使得该线程停止它正在做的无论它是阻塞在读方法中还是一个可被中断的blocking方法中。

### 7.1.7. 使用newTaskFor方法来封装非标准取消方式

ReaderThread类中使用的用来封装非标准取消方式的技术可以使用在java6中ThreadPoolExecutor类中新增的newTaskFor钩子方法来优化。当一个Callable被提交给一个ExecutorService，submit方法返回一个Future实例，该实例能够用来取消任务。newTaskFor钩子方法是一个工厂方法，用来创建代表任务的Future实例。该方法返回一个RunnableFuture实例，RunnableFuture是一个同时继承了Future和Runnable接口的接口（FutureTask类实现了该接口）。

定制任务的Future使得你可以覆写Future的cancel方法。定制的cancellation代码可以在任务取消时执行日志记录或者收集数据，也可以用来取消那些无法响应中断的活动。ReaderThread类通过覆写interrupt方法来封装对使用socket的线程的取消。

[Listing 7.12]()定义了一个CancellableTask接口，该接口继承了Callable接口，并增加了一个cancel方法和一个newTask工厂方法来构建RunnableFuture。CancellingExecutor类继承了类ThreadPoolExecutor，并覆写了newTaskFor()方法来允许CancellableTask创建它自己的Future。
#### Listing 7.12 使用newTaskFor方法来封装对一个任务的取消
```
public interface CancellableTask<T> extends Callable<T>{
	void cancel();
	RunnableFuture<T> newTask();
}

@ThreadSafe
public class CancellingExecutor extends ThreadPoolExecutor{
	...
	protected <T> RunnableFuture<T> newTaskFor(Callable<T> callable){
		if(callable instanceof CancellableTask){
			return ((CancellableTask<T>)callable).newTask();	
		}esle{
			return super.newTaskFor(callable);
		}
	}	
}

public abstract class SocketUsingTask<T> implements CallcellableTask<T>{
	@GuardedBy("this")
	private Socket socket;
	protected synchronized void setSocket(Socket s){
		socket=s;
	}
	public synchronized void cancel(){
		try{
			if(socket!=null){
				socket.close();
			}
		}catch(IOException ignored){
		}
	}
	public RunnableFuture<T> newTask(){
		return new FutureTask<T>(this){
			public boolean cancel(boolean mayInterruptIfRunning){
				try{
					SocketUsingTask.this.cancel();
				}finally{
					return super.cancel(mayInterruptIfRunning);
				}
			}
		}
	}
}
```
SocketUsingTask实现了CancellableTask接口，并定义了Future的cancel方法来关闭socket,也调用了super.cancel方法。如果SocketUsingTask通过它的Future类实例来取消，socket被关闭，正在执行的线程被中断。这增加了该任务对取消的响应：它不计能安全的调用可被中断的阻塞方法，也能调用阻塞的socket I/O方法，同时能够保留对中断的响应能力。
